name: Run Unittests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Adjust to your project's Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Run tests
      run: |
        cd test
        python -m unittest discover
